#### Install the ucimlrepo package

In [ ]:
pip install ucimlrepo

#### Import the dataset into your code

In [ ]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
adult = fetch_ucirepo(id=2) 
  
# data (as pandas dataframes) 
X = adult.data.features # independent variables
y = adult.data.targets  # dependent variables
  
# metadata 
print(adult.metadata) 
  
# variable information 
print(adult.variables)

#### The dataset is the Census Income dataset.
 The Census Income dataset is a multivariate dataset containing several categorical features related to individuals, 
<br> such as age, education, occupation, and hours worked per week.
<br> It has 48842 Instances
<br> Features 14 including target value

In [41]:
df = pd.concat([X, y], axis=1)
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

#### A clean subset of the data has been extracted using the following conditions:
Condition	
<BR>AAGE > 16	Includes only individuals older than 16 (removes children)
<BR>AGI > 100	Ensures only those with some income are included
<BR>AFNLWGT > 1	Ensures positive sampling weight (each person represents at least one)
<BR>HRSWK > 0	Includes only those who work at least 1 hour per week

In [50]:
df['status'] = df['age'].apply(lambda x: 'All' if x > 16 else 'not working')
df['status'].count()

48842

#### Features - Independent Variable

In [37]:
X.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba

#### Target - dependent Variable

In [36]:
y.head()

  income
0  <=50K
1  <=50K
2  <=50K
3  <=50K
4  <=50K

#### Problem Statement: Predicting Income using the Census Income Dataset

Now we have to build a predictive supervised machine learning model
<br> to predict whether a person earns more than $50,000 per year. 
<br> This is  binary classification as we have supervised and labelled data 
<br> where the target variable, income, has two categories:
<br> Class 1: <=50K 
<br> Class 2: >50K

#### Machine Learning Approach
 Supervised Learning: Uses labelled data (input features + output labels) to train the model.
<BR> We use 80% of the data for training and the rest for testing.
<BR> Goal: Achieve high accuracy (e.g., >90%) on unseen test data.

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       47879 non-null  object
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  object
 4   education-num   48842 non-null  int64
 5   marital-status  48842 non-null  object
 6   occupation      47876 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   sex             48842 non-null  object
 10  capital-gain    48842 non-null  int64
 11  capital-loss    48842 non-null  int64
 12  hours-per-week  48842 non-null  int64
 13  native-country  48568 non-null  object
 14  income          48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [46]:
df.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [45]:
df.isnull().sum()

age                 0
workclass         963
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation        966
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
income              0
dtype: int64